packages:
  - apps/*
  - packages/*
  - tools/*
  - examples/*

catalog:
  "@types/node": ^24
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  react: ^19.2.5
  react-dom: ^19.2.5
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vite-plus: 0.3.1

catalogMode: prefer
overrides:
  "@strator/core": link:packages/core
  "@strator/react": link:packages/react
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
